name: CI

on:
  push:
    # This captures EVERY push to ANY branch to ensure we trigger
    branches: ["**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CORTEX_URL: ${{ vars.CORTEX_URL }}
      API_ID: ${{ vars.API_ID }}
      API_KEY: ${{ secrets.API_KEY_X5_PROD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Extract Image Name from Dockerfile
        id: get_name
        run: |
          # Grabs the base image name (e.g., alpine:3.20.8)
          DOCKER_BASE=$(grep "^FROM" Dockerfile | tail -n 1 | awk '{print $2}')
          echo "IMAGE_NAME=$DOCKER_BASE" >> $GITHUB_ENV
          echo "Extracted Name: $DOCKER_BASE"

      # --- MODE 1: BUILD (Active) ---
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      # --- MODE 2: LOAD (Commented out) ---
      # To use this, put a '#' in front of the Build step above and remove '#' below
      # - name: Docker load and Rename
      #   run: |
      #     LOAD_OUT=$(docker load -i 04051405_2026-05-26_etf-ordenes-front.tar)
      #     IMG_ID=$(echo "$LOAD_OUT" | grep -oE 'sha256:[a-f0-9]+|Loaded image: .*' | sed 's/Loaded image: //')
      #     docker tag "$IMG_ID" $IMAGE_NAME

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y libhyperscan5 jq

      - name: Cortex CLI install
        run: |
          crtx_resp=$(curl -s "$CORTEX_URL/public_api/v1/unified-cli/releases/download-link?os=linux&architecture=amd64" \
            -H "x-xdr-auth-id: $API_ID" \
            -H "Authorization: $API_KEY")
          crtx_url=$(echo $crtx_resp | jq -r ".signed_url")
          curl -L -o cortexcli "$crtx_url"
          chmod +x cortexcli

      - name: Cortex CLI execution
        run: |
          sudo ./cortexcli --log-level debug --api-base-url "$CORTEX_URL" --api-key "$API_KEY" --api-key-id "$API_ID" image scan --timeout 600 "$IMAGE_NAME"